permalink: /:year/:month-:day-:title.html
markdown: rdiscount
destination: _site
url: one-point.github.io
name: 每小题1分
author: One-Point
email: wlzhizhen@163.com
duoshuo: one-point
github: one-point
pygments: true
safe: false
paginate: 20
truncate: 70
tkurl: onepoint.tk
auto: true
